import asyncio
import logging
from concurrent import futures
import grpc

from src.config.environment import env_config
from src.orchestration import MasterOrchestrator

# Import your compiled gRPC code footprints
from generated import ingress_pb2
from generated import intent_pb2
from generated import intent_pb2_grpc  # Generated by grpc_tools.protoc

logger = logging.getLogger("src.main_grpc")


class IntentServiceServicer(intent_pb2_grpc.IntentServiceServicer):
    """
    Implements the gRPC service interface compiled from your protocol buffer specification.
    """
    def __init__(self):
        # Instantiate your orchestrator which manages the underlying pipelines
        self.orchestrator = MasterOrchestrator()

    async def ProcessIntentStream(
        self, 
        request: ingress_pb2.IngressPayload, 
        context: grpc.aio.ServicerContext
    ) -> intent_pb2.IntentPayload:
        """
        gRPC Remote Procedure Call (RPC) handler. Receives strongly-typed binary
        IngressPayload blocks directly over an HTTP/2 multiplexed connection.
        """
        logger.info(f"Intercepted inbound gRPC service payload track type: {request.input_type}")

        try:
            # 1. Dispatch the native protobuf structure straight to the Master Orchestrator
            validated_payload, action_status = await self.orchestrator.route_and_execute(request)
            
            # 2. Handle Hard Guardrail security blocks or ceiling breaches
            if action_status == "BLOCK":
                logger.critical(f"Aborting gRPC pipeline execution loop. Threat status: {action_status}")
                # Abort the RPC call with an explicit gRPC Status Code mapping
                await context.abort(
                    grpc.StatusCode.FAILED_PRECONDITION,
                    f"Transaction Gating Error: {validated_payload.status_message}"
                )

            # 3. Success / Remediation: Return the actual, compiled IntentPayload proto instance
            # validated_payload is already an instance of intent_pb2.IntentPayload
            return validated_payload

        except ValueError as security_firewall_err:
            logger.critical(f"gRPC Layer intercepting acute payload exception: {str(security_firewall_err)}")
            await context.abort(
                grpc.StatusCode.PERMISSION_DENIED,
                f"Security Guardrail Violation: {str(security_firewall_err)}"
            )
        except Exception as system_err:
            logger.error(f"Internal gRPC unhandled runtime error: {str(system_err)}")
            await context.abort(
                grpc.StatusCode.INTERNAL,
                "Internal service processing failure encountered."
            )


async def serve():
    """
    Boots up the high-performance Asynchronous gRPC Server.
    """
    # Create the async server instance bound to an execution thread pool
    server = grpc.aio.server(futures.ThreadPoolExecutor(max_workers=10))
    
    # Register your servicer implementation class with the running gRPC matrix
    intent_pb2_grpc.add_IntentServiceServicer_to_server(IntentServiceServicer(), server)
    
    # Listen globally over port 50051 (Standard internal microservice port configuration)
    listen_addr = "[::]:50051"
    server.add_insecure_port(listen_addr)
    
    logger.info(f"Asynchronous gRPC Service Core initialized on connection layer {listen_addr}")
    logger.info(f"System Maximum Transfer Ceiling verified at: {env_config.SYSTEM_MAX_CEILING}")
    
    await server.start()
    
    # Keep the server alive loop active until explicitly terminated
    try:
        await server.wait_for_termination()
    except asyncio.CancelledError:
        logger.info("Shutdown event intercepted. Stopping gRPC server sockets safely...")
        await server.stop(grace=5.0)


if __name__ == "__main__":
    # Configure production terminal logging footprints
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    )
    
    # Boot the async loop execution pool
    try:
        asyncio.run(serve())
    except KeyboardInterrupt:
        logger.info("Microservice offline.")